-- Create products table
create table public.products (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  price text not null,
  image_url text not null,
  buy_link text not null,
  is_visible boolean default true,
  category text not null
);

-- Set up Row Level Security (RLS)
alter table public.products enable row level security;

-- Create policy to allow public read access
create policy "Enable read access for all users"
on public.products
for select
using (true);

-- Create policy to allow authenticated users (admin) to insert, update, delete
-- Note: You need to configure auth policies according to your auth setup.
-- For now, we'll allow all operations for simplicity in development, 
-- BUT in production you should restrict this to authenticated users only.
create policy "Enable all access for all users (DEV ONLY)"
on public.products
for all
using (true)
with check (true);
